allow:
  # ip4:
  #   - 127.0.0.1/24
  # ip6:
  #   - ::1/128
  # domain:
  #   - "localhost"
  # process:
  #   - "curl"
block:
  # ip4:
  #   - 172.67.195.193/32
  # ip6:
  #   - 2606:4700:3031::6815:4c8b/128
  # domain:
  #   - "evil.com"
  # process:
  #   - "wget"
